name: Deploy Express.js App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy:
    needs: build

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4  

